### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by rupalitanna0** [rupalitanna0/blackjack#5]
@DBrodsky90 
 not sure how to get stand working
winner loop issue
hey i m trying to setup hit function the image comes up not able to do with point it doubles up
i m not sure how to get the same cards from the player's in stand function
my winner loop just does work it just exits

**Comment by awongh** [comment]
hi, can you please be more specific about what your problem is?

Please say:

 1. what is the exact problem.
 - what is the behavior you are trying to get working?
 - are you getting any errors and if you are, include the exact text of the errors
 - if you are not getting any errors, please say what is happening/not happening
 - what have you tried to fix the problem? please be specific about how you tried to fix things and why.
 - link any code that you think is relevant here. (you can link to the github page/line of code) - (example: https://github.com/rupalitanna0/blackjack/blob/master/js/dealer.js#L4)
 - write more and be more specific than you think is necessary- the more context there is the easier it will be for us to understand what your problem is.

thanks!

**Comment by rupalitanna0** [comment]
My hit Function doubles up the points;
i m trying to add up the value of card coming when hit it clicked,
no error
the points double up and my bust thing in Winner is not working well too
i tried to use getValue function and get points but that didnt work i tried to call getValue function in hit but no joy

**Comment by awongh** [comment]
sorry, but I still need more information. 

- "my bust thing in Winner is not working well too" is not helpful - is this a different issue from the one you are discussing with "hit function"?

- can you please link to some code as in my example above? please link to the specific functions that you are talking about 

- if I download and run your code can you please give detailed instructions about how I can get this error to happen for me?

thanks!
